[book]
authors = ["Jacek Sieka"]
language = "en"
src = "src"
title = "Chronos"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 2

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]
git-branch = "master"

[output.html]
git-repository-url = "https://github.com/status-im/nim-chronos/"
additional-css = ["open-in.css"]
